services:
  web:
    image: yugansharora01/docchat:latest
    container_name: docchat_web
    env_file:
      - .env.production
    restart: always
    volumes:
      - static_volume:/vol/static

  nginx:
    image: nginx:stable
    container_name: docchat_nginx
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volumes:/vol/static:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/letsencrypt:ro
  
  volumes:
    static_volume: